worker_processes 1;
pid /var/run/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    access_log    /dev/stdout;

    server {
        listen 8099;
        root /var/www/html;
        index index.html;

        # Serve the dashboard
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Dynamically generated proxy locations for each GivTCP instance.
        # Written by /etc/cont-init.d/50-generate-config.sh at startup.
        include /etc/nginx/conf.d/proxy.conf;
    }
}
